Tetas.Front/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Tetas.Domain;
using Tetas.Front.Helpers;
using Tetas.Front.Models;
using Tetas.Tools;

namespace Tetas.Front.Controllers
{
    public class GroupsController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        // GET: Groups
        public async Task<ActionResult> Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var groups = db.Groups.Include(g => g.GroupType).Include(g => g.User)
                .Where(p => p.UserId == (int)id);
            return View(await groups.ToListAsync());
        }

        public async Task<int> GetUserId()
        {
            //if (Session["UserId"] != null && Convert.ToInt32(Session["UserId"]) != 0) return Convert.ToInt32(Session["UserId"]);
            var manager =
                new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            if (currentUser != null)
            {
                return await UsersHelper.GetUserId(currentUser.Email);
            }
            return 0;
            // Session["UserId"] =

            //return Convert.ToInt32(Session["UserId"]);
        }
        public async Task<ActionResult> IndexRequest(int id)
        {
            var userId = await GetUserId();
            ViewBag.ConectedUserId = userId;
            var member = db.GroupMembers.Where( p=>p.GroupId==id)
                .Include(g => g.User)
                .Include(u => u.Group);

            return View(await member.ToListAsync());
        }

        public async Task<ActionResult> IndexAll()
        {
            var userId = await GetUserId();
            ViewBag.ConectedUserId = userId;
            var groups = db.Groups.Include(g => g.GroupType)
                .Include(g => g.User)
                .Include(u => u.GroupMembers);
            return View(await groups.ToListAsync());
        }
        public async Task<ActionResult> Apply(int id)
        {
            var userId = await GetUserId();

            var group = db.Groups.FindAsync(id);

            if (group == null)
            {
                return View("Error");
            }

            var member = new GroupMember
            {
                UserId = userId,
                StatusId = 6,
                GroupId = id,
                ApplicationDate = DateTime.Now.ToUniversalTime()
            };

            db.GroupMembers.Add(member);

            await db.SaveChangesAsync();

            return RedirectToAction("IndexAll");
        }

        public async Task<ActionResult> ManageUsers(int id, int statusid, int groupid)
        {
            var member = await db.GroupMembers.FirstOrDefaultAsync(p => p.UserId == id && p.GroupId == groupid);

            if (member == null)
            {
                return HttpNotFound();
            }

            member.StatusId = statusid;

            return RedirectToAction($"Details/{groupid}");
    }
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userId = await GetUserId();
            var group =  db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.ConectedUserId = userId;
            return View(group);
        }

        // GET: Groups/Create
        public async Task<ActionResult> Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.GroupTypeId = new SelectList(db.GroupTypes, "GroupTypeId", "Name");
            ViewBag.PrivacyId = new SelectList(db.Privacies, "PrivacyId", "Name");

            var newGroup = new GroupView { UserId = (int)id };
            return View(newGroup);
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(GroupView view)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                const string folder = "~/Content/GroupPics";

                if (view.ImageFile != null)
                {
                    pic = Files.UploadPhoto(view.ImageFile, folder, "");
                    pic = string.Format("{0}/{1}", folder, pic);
                }
                var group = new Group
                {
                    CreationDate = DateTime.Today.ToUniversalTime(),
                    GroupId = view.GroupId,
                    UserId = view.UserId,
                    GroupTypeId = view.GroupTypeId,
                    Link = view.Link,
                    Name = view.Name
                };

                group.Picture = pic;

                db.Groups.Add(group);
                await db.SaveChangesAsync();

                var member = new GroupMember
                {
                    UserId = view.UserId,
                    GroupId = group.GroupId,
                    ApplicationDate = DateTime.Today.ToUniversalTime(),
                    StatusId = 1
                };

                db.GroupMembers.Add(member);

                await db.SaveChangesAsync();

                return RedirectToAction($"Index/{view.UserId}");
            }

            ViewBag.GroupTypeId = new SelectList(db.GroupTypes, "GroupTypeId", "Name", view.GroupTypeId);
            return View(view);
        }

        // GET: Groups/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FindAsync(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupTypeId = new SelectList(db.GroupTypes, "GroupTypeId", "Name", group.GroupTypeId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email", group.UserId);
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "GroupId,GroupTypeId,UserId,Name,Link,Picture,CreationDate")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.GroupTypeId = new SelectList(db.GroupTypes, "GroupTypeId", "Name", group.GroupTypeId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email", group.UserId);
            return View(group);
        }

        // GET: Groups/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FindAsync(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Group group = await db.Groups.FindAsync(id);
            db.Groups.Remove(group);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tetas.Front/Controllers/UserPostsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Tetas.Domain;
using Tetas.Front.Helpers;
using Tetas.Front.Models;

namespace Tetas.Front.Controllers
{
    public class UserPostsController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        public async Task<int> GetUserId()
        {
            //if (Session["UserId"] != null && Convert.ToInt32(Session["UserId"]) != 0) return Convert.ToInt32(Session["UserId"]);
            var manager =
                new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());
            // Session["UserId"] =
            return await UsersHelper.GetUserId(currentUser.Email);
            //return Convert.ToInt32(Session["UserId"]);
        }

        #region Comments
        public async Task<ActionResult> CreateComment(int id)
        {
            var userId = await GetUserId();

            var userPost = await db.UserPosts.FindAsync(id);
            if (userPost == null)
            {
                return HttpNotFound();
            }
            var comment = new PostComment
            {
                UserPostId = id,
                UserId = userId
            };

            return View(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateComment(PostComment comment)
        {
            if (ModelState.IsValid)
            {
                comment.CommentDate = DateTime.Now.ToUniversalTime();
                db.PostComments.Add(comment);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(comment);
        }

        public async Task<ActionResult> EditComment(int id)
        {
            var userId = await GetUserId();

            var comment = await db.PostComments.FindAsync(id);
            if (comment == null)
            {
                return View("Error");
            }
            //supposily the user than is editing is the logged user, but let's validate 
            return comment.UserId != userId ? View("Error") : View(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditComment(PostComment comment)
        {
            if (!ModelState.IsValid) return View(comment);
            comment.ModifiedDate = DateTime.Now.ToUniversalTime();
            db.Entry(comment).State=EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> DeleteComment(int id)
        {
            //  var userPost = await db.UserPosts.FindAsync( id);

            var comment = await db.PostComments.FindAsync(id);
            if (comment == null)
            {
                return View("Error");

            }
            
            db.PostComments.Remove(comment);

            try
            {
                await db.SaveChangesAsync();
            }
            catch (Exception e)
            {
                return View("Error");
            }

            return RedirectToAction("Index", "Home");


        }
        #endregion

        #region Post




        public async Task<ActionResult> Index()
        {
            var userPosts = db.UserPosts.Include(u => u.User);

            return View(await userPosts.ToListAsync());
        }

        // GET: UserPosts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserPost userPost = await db.UserPosts.FindAsync(id);
            if (userPost == null)
            {
                return HttpNotFound();
            }
            return View(userPost);
        }


        public async Task<ActionResult> Create()
        {
            var userId = await GetUserId();
            var userPost = new UserPost { UserId = userId };
            return View(userPost);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UserPost userPost)
        {
            if (ModelState.IsValid)
            {
                userPost.PostDate = DateTime.Now.ToUniversalTime();
                db.UserPosts.Add(userPost);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.UserId = new SelectList(db.Users, "UserId", "Email", userPost.UserId);
            return View(userPost);
        }

        // GET: UserPosts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userId = await GetUserId();
            var userPost = await db.UserPosts.FindAsync(id);
            if (userPost == null)
            {
                return HttpNotFound();
            }

            userPost.UserId = userId;

             return View(userPost);
        }

        // POST: UserPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UserPost userPost)
        {
            if (!ModelState.IsValid) return View(userPost);
            db.Entry(userPost).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
          //  var userPost = await db.UserPosts.FindAsync( id);

          var userPost = await  db.UserPosts.Include(p=>p.PostComments).FirstOrDefaultAsync(p=>p.UserPostId==id);
            if (userPost == null)
            {
                return View("Error");

            }

            foreach (var comment in userPost.PostComments.ToList())
            {
                try
                {
                    //if (userPost.PostComments.All(c => c.PostCommentId != comment.PostCommentId))
                       // db.PostComments.Remove(comment);
                 var commToDelete =  await db.PostComments.FindAsync(comment.PostCommentId);

                     if (commToDelete != null) db.PostComments.Remove(commToDelete);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
               
            }
            try
            {
                await db.SaveChangesAsync();
            }
            catch (Exception e)
            {
                return View("Error");
            }

            db.UserPosts.Remove(userPost);

            try
            {
                await db.SaveChangesAsync();
            }
            catch (Exception e)
            {
                return View("Error");
            }

            return RedirectToAction("Index", "Home");
           
          
        }


        #endregion
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tetas.Front/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
@*<h2>@ViewBag.Title.</h2>*@
<h3>@ViewBag.Message</h3>
<br/>
<h1>
    Track Education For Teachers and Students
</h1>
<hr/>
<p style="font-size: x-large;color:cornflowerblue">
    Tetas is an open source social networking web application that 
    provides a robust app on which to build all kinds of social environments,
    from a campus wide social network for your university, school or college 
    or an internal collaborative platform for your organization through to a 
    brand-building communications tool for your company and its clients. But 
    the main goal is communicate teachers and student than need to be connected 
    but don’t want to mix personal and professional environments.
</p>

Tetas.Front/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Tetas.Front/Views/Home/Index.cshtml
@using System.Diagnostics
@using Tetas.Domain
@model IEnumerable<Tetas.Domain.UserPost>

@{
    ViewBag.Title = "Home";
}
<br /><br />

<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
        
    </div>
    <div class="col-md-2">
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div id="GroupTab">
            <h4>My Groups</h4><br />
            <div>    @Html.ActionLink("New Group", "Create", "Groups", new { id = @ViewBag.ConectedUserId }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Manage Groups", "Index", "Groups", new { id = @ViewBag.ConectedUserId }, new { @class = "btn btn-info" })
            </div>
            <table class="table">
                
                @{
                    UserPost first = null;
                    foreach (var p in Model)
                    {
                        if (p.UserId == @ViewBag.ConectedUserId)
                        {
                            first = p;
                            break;
                        }
                    }
                    if (first !=null && first.User != null)
                    {
                        var user = first.User; 
                        if (user.Groups == null || user.Groups.Count == 0)
                        {
                            <tr>
                                <td>
                                    Theres No Groups, create one to begin the magic
                                </td>
                                <td></td>
                            </tr>

                        }
                        else
                        {
                            foreach (var group in user.Groups)
                            {
                                //if (item.User.Groups == null || item.User.Groups.Count==0)


                                {
                                
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => group.Name)
                                        </td>
                                        <td>
                                            @Html.ActionLink("View Group", "Details","Groups", new { id = group.GroupId },new{}) 
                                        </td>
                                    </tr>
                                
                                }
                            }

                        }
                    }

                    
                }



            </table>
        </div>


    </div>
    <div class="col-md-8">
        @Html.ActionLink("New Post", "Create", "UserPosts", new { }, new { @class = "btn btn-primary" })
       | @Html.ActionLink("Discover Groups", "IndexAll", "Groups", new { }, new { @class = "btn btn-info" })
        <br /><br />

        @foreach (var item in Model)
        {
            <div class="form-group">
                <div class="col-md-1">

                    @{
                        var firstOrDefault = item.User;
                    }
                    @if (firstOrDefault != null && !string.IsNullOrEmpty(firstOrDefault.Picture))
                    {
                        <img src="@Url.Content(item.User.Picture)" alt="Image" style="width: 50px;height:50px" />
                    }
                </div>
                <div class="col-md-11">
                    <span style="font-weight: bold;color:blue">
                        @Html.DisplayFor(modelItem => item.User.Name)
                        @Html.DisplayFor(modelItem => item.User.LastName)
                    </span> post on <span style="font-size:small">  @Html.DisplayFor(modelItem => item.PostDate)</span>
                    <p style="font-weight: bold">
                        @Html.DisplayFor(modelItem => item.HeadPost)

                    </p>
                    <p style="">
                        @Html.DisplayFor(modelItem => item.StrPost)
                    </p>
                    @Html.ActionLink("Comment Post", "CreateComment", "UserPosts", new { id = item.UserPostId }, new { }) &nbsp;
                    @if (item.UserId == @ViewBag.ConectedUserId)
                    {
                        @Html.ActionLink("Edit Post", "Edit", "UserPosts", new { id = item.UserPostId }, new { })
                        <a>&nbsp;</a>
                        @Html.ActionLink(
                            "Delete Post",
                            "Delete",  "UserPosts",
                            new { id = item.UserPostId },
                            new { onclick = "return confirm('Are you sure you wish to delete this post and all their comments on it?');" })

                    }
                    <br />  <br />
                </div>
            </div>


            <br />
            <br /> <br />

            foreach (var item2 in item.PostComments)
            {
                <div style="padding-left: 60px">
                    <div class="col-md-1">
                        @if (!string.IsNullOrEmpty(item2.User.Picture))
                        {
                            <img src="@Url.Content(item2.User.Picture)" alt="Image" style="width: 40px;height:40px" />
                        }
                    </div>
                    <div class="col-md-11">
                        <span style="font-size: large;color:green"> @Html.DisplayFor(modelItem => item2.User.Name)</span>
                        comment on <span style="font-size: small"> @Html.DisplayFor(modelItem => item2.CommentDate)</span>

                        <p style="color: black"> @Html.Raw(item2.StrComment) </p>
                        @if (item2.UserId == @ViewBag.ConectedUserId)
                        {
                            @Html.ActionLink("Edit comment", "EditComment", "UserPosts", new { id = item2.PostCommentId }, new { })
                            <a>&nbsp;</a>
                        }

                        @if (item.UserId == @ViewBag.ConectedUserId || item2.UserId == @ViewBag.ConectedUserId)
                        {
                            @Html.ActionLink(
                                "Delete comment",
                                "DeleteComment",  "UserPosts",
                                new { id = item2.PostCommentId },
                                new { onclick = "return confirm('Are you sure you wish to delete this comment?');" })

                        }
                    </div>
                </div>
                <br /> <hr />
            }

            <br /><br />
            <hr />
        }

    </div>
    
</div>

Tetas.Front/Views/Home/_GroupsListPartial.cshtml
@model IEnumerable<Tetas.Domain.Group>

<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("View Group", "Edit", new { id = item.GroupId }) |
            </td>
        </tr>
    }

</table>